name: Run Selenium Tests
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 22
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '22'
          java-package: jdk
          architecture: x64
          check-latest: false
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: mvn install
        working-directory: ./GoodReads-Automation-Project-with-Selenium
      - name: Run Selenium Tests
        run: mvn test
